### ISSUE TITLE
Infinite loop in propnet generation for Stanford TicTicToe

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#158]
If the GDL has 'input' defs that do not cover the legal/does forms then propnet generation will loop infinitely in getTopologicalOrdering().  Stanford TicTicTo is an example of this

**Comment by arr28** [comment]
Note that this is tic **tic** toe (not the standard TTT).

**Comment by arr28** [comment]
Also, this game has now been removed from the Stanford repository.

We're talking about illegal GDL.  We aren't aware of any games that have this flaw any more.  If there is one, we log a suitable warning.  No point in having this issue open still.
