### ISSUE TITLE
Add dead match reaper

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#162]
Something to kill off an in-progress game if no communication from server for a lengthy period (configurable, default 30 mins, with negative implying off)

**Comment by arr28** [comment]
Got stuck on Tiltyard today.  Missed a message from the server completely.

```
26/05/2015, 13:19:02.673	DEBUG	GGP-Match-Step: 1
26/05/2015, 13:19:24.026	DEBUG	GGP-Match-Step: 2
26/05/2015, 13:20:24.834	DEBUG	GGP-Match-Step: 4
```

Sequence is then fine until the last turn received...

```
26/05/2015, 13:26:54.984	DEBUG	GGP-Match-Step: 22
...
26/05/2015, 13:27:11.718	DEBUG	Factor best move: noop
26/05/2015, 13:27:11.718	INFO	Playing move: noop
```

And then we go on thinking but never hear from the server again.  Server logs say the game stopped after turn 43 - and shows our opponent (Galvanise) as responsive during that time.

**Comment by arr28** [comment]
Watchdog framework added.  Doesn't actually do anything when the watchdog expires though (other than make a log).  It might be as simple as just needing to call `tidyUp()`, but there might well be threading issues to deal with and additional state to tidy up "below" Sancho.

**Comment by arr28** [comment]
Completed.
