### ISSUE TITLE
Integrate Alex's OPNF fixes

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#212]
See his post at http://ggp.boards.net/thread/94/bug-fixes-base-proverstatemachine-opnf.

**Comment by arr28** [comment]
I've merged in the second of his two fixes.  The other (https://github.com/ggp-org/ggp-base/commit/54e5514d0c58f0f00f30560b9a00d07554a778ee) is still to come.

**Comment by arr28** [comment]
Whilst the second fix only affects the ProverStateMachine...

1. This is the machine used by the Server app.
2. The fix includes some test cases which we should definitely run against the FDRPSM to ensure that we'll be able to handle games with the same rule patterns.

**Comment by arr28** [comment]
The new test case 5D that Alex added to `ProverStateMachineTests`, doesn't work when run against a PropNetStateMachine (created with the OPNF).

It gets stuck in an infinite loop in `OPNF#getTopologicalOrdering`.  Each time an item is removed from the queue, a new one is added.  After dealing with some initial sentence forms, the queue gets stuck at length 4.  The queue is always a cyclic permutation of `[( init ( sTrue _ _ ) ), ( r _ _ ), ( s _ _ ), ( init ( rTrue _ _ ) )]`.  Each time round the loop, the item at the head is removed and then added back to the tail.

**Comment by AlexLandau** [comment]
This is sort of tracked by the TODO in that method: //TODO: Add check for an infinite loop here, or stratify loops

There's a better toposort algorithm that handles this case in DependencyGraph#toposortSafe. However, there are probably other changes that need to be made to the OPNF to accommodate dealing with a stratum of sentence forms at a time.

**Comment by arr28** [comment]
The new case 5D still doesn't work with OPNF.  Alex has a TODO marker and, for now, we'll just hope this doesn't come up in practise.  Closing.
