### ISSUE TITLE
Network split on the wrong proposition?

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#217]
I believe (without reference to the code) that we do the X-/O-Net split on the proposition that changes most frequently in sample playouts.  This mechanism tends to catch the control proposition because the control proposition typically changes every turn (or perhaps every other turn).  For some games though (of which Kalaha is particularly notable), we catch a different proposition instead because the control proposition doesn't actually change very often.

As I understand it, the advantage of network split is a reduction in the number of components that we need to propagate changes through.

I have a hypothesis that (for best perf.) we shouldn't actually be splitting on the most frequently changing proposition.  A better approach *might* be to split on the proposition whose change is correlated with the largest change of other propositions.

Probably better still, we could multiply the proposition change frequency by the average impact of changing that proposition.  (After all, there's no point in splitting on a proposition that has large impact if it basically never changes.  Although, having said that, it would be interesting to see whether we do better in w/Pie games by splitting on the pie proposition rather than the control proposition.  Probably not, but I might take a look.)

**Comment by arr28** [comment]
Changing the splitting manually, measuring with `StateMachinePerformanceAnalyser -statemachine -time30 hexPie` and averaging over 3 runs...

- "control player2" (automatically identified) gives 801 rollouts/s
- "usingMarker player1 red" (hand-identified pie prop) gives 915 rollouts/s

So, a 15% improvement by splitting on the pie prop.  Interestingly, this *isn't* because of a smaller network when splitting on the pie prop - because the network is actually slightly larger (82.9K vs 82.3K).

I wonder if it's because splitting isn't very useful at all in this game and we get better cache performance by splitting on a proposition which almost never changes.

**Comment by arr28** [comment]
In Kalaha, the automatically chosen proposition is "hand north s0".  Splitting on "control north" instead gives performance ~1% better (probably within measurement error).  The X-Net grows ever so slightly with the hand-picked split prop (50,694 vs 50,680 originally) and the O-Net shrinks substantially (36,437 vs 46,468 originally) but the smaller O-Net hasn't significantly improved performance.

**Comment by arr28** [comment]
Back on Hex, note that splitting on "usingMarker player1 blue" doesn't do quite so well (885 rollouts/s).  Presumably that's because that vast majority of random games will stick with player 1 as red (because the option to swap roles is buried amongst 80 hexes to be played).

**Comment by SteveDraper** [comment]
Sounds like a good idea

**Comment by arr28** [comment]
Infuriatingly, the advantages seen by splitting hexPie on the "usingMarker player1 red" aren't reproducible on my PC (only on the laptop).  The PC gets identical results (1074 rollouts/s) whether splitting on "usingMarker player1 red" or "control player2".

Not splitting at all makes things slightly worse (1050 rollouts/s).

**Comment by arr28** [comment]
Kalaha on the PC shows no change in rollout perf. when splitting differently (which is the same as the laptop).  ~630 rollouts/s on the PC.

**Comment by arr28** [comment]
So this idea is basically a failure.  Most games were choosing a sensible splitting prop in the first place and in the few that weren't, there's no reliable improvement from a hand-picked split prop.  No point in making the split-prop logic more complicated.
