### ISSUE TITLE
Wrong move played in 2-player guess two-thirds

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#237]
In [this match](http://www.ggp.org/view/tiltyard/matches/c45b24b3c366ba850a09585c646ce60e2f55eda9/), we played 67 (and lost).

The correct play is *always* 0 (for this 2-player variant).  Whoever picks the smallest number wins.

**Comment by SteveDraper** [comment]
Now it has switched to using MCTS (not iterated) it play 0 correctly.
