### ISSUE TITLE
Poor hex play

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#240]
In [this match](http://www.ggp.org/view/tiltyard/matches/1086cd94f8a71d233033ae881f2fc6578041f72d/), playing c4 was surely wrong.  The double c4/c5 and a5/a6 meant that the top was already sown up.  However, the bottom wasn't yet.  An opponent play at g4 would have stopped us.

I suspect this is just a case of Hex being too hard.  Not at all urgent, but perhaps useful to have a clear example if we ever try to do anything with Hex.

**Comment by arr28** [comment]
We lost two matches of Hex today.  The [first match](http://www.ggp.org/view/tiltyard/matches/f98965e97b538fe5a10abe89d947d0cd46266b83/) was Hex w/Pie and we were playing second.  The [second match](http://www.ggp.org/view/tiltyard/matches/27ddc4e99a1b8bca5514e9a52e2203bbc8aac52c/) was plain Hex and we were playing first.  So we were in the provably winning role in both cases.

I haven't yet analysed where I think we went wrong.

**Comment by arr28** [comment]
Logs are only available locally for [match 1](http://localhost:9199/localview/tiltyard.hexPiev0.1430752539154) and [match 2](http://localhost:9199/localview/tiltyard.hexv0.1430757955460).

Nothing looks unusual about the logs for the first match.  (No especially wild swings in expected score, no logs of the wrong move being played, no GC spikes, sample rate stayed at 1 throughout, rollout rate was lightly clustered around the 2K/s mark.)

**Comment by arr28** [comment]
Oh, in both cases, we were playing against "General".

If the first match, we ought to have invoked Pie (but didn't).  Then, our third play of h3 was unhelpful as was the follow-up.

In the second match, our 4th play of e7 was a shocker.  We should have either played f6 (same basic idea but a move quicker) or c6.

```
04/05/2015, 17:54:17.863	INFO	Move ( place f 6 ) scores 57.41 (selectionScore score 53.61, selection count 13312, ref 34359941367)
04/05/2015, 17:54:17.872	INFO	Move ( place c 6 ) scores 55.49 (selectionScore score 50.54, selection count 5376, ref 34359842968)
04/05/2015, 17:54:17.877	INFO	Move ( place e 7 ) scores 59.48 (selectionScore score 54.20, selection count 5427, ref 34359840538)
04/05/2015, 17:54:17.877	INFO	Most likely path: ( place e 7 ), ( place c 6 ) | ( place i 6 ), ( place f 6 ) |
```

Interesting that we knew the follow-up that was coming, but still made the wrong choice.

Our next play of b9 was completely futile.  After that, I'm not surprised we lost.

I wonder if our playing strength at Hex has deteriorated at some point.  I remember us playing pretty solid games in the past.

**Comment by SteveDraper** [comment]
I bet RAVE would work well in Hex

**Comment by arr28** [comment]
Just discovered that I've been playing for ~24 hours with a fixed sample size of 1.  Don't know if that might have been responsible.  As a game that's as wide as it is deep, it's quite possible that we normally get a moderately high sample rate (because the tree thread is busy with expansions).

I'm not sure if I've kept any logs that'll tell me.

**Comment by arr28** [comment]
I'm going to put this one down to misconfiguration (running at ~25% of normal processing power).

**Comment by arr28** [comment]
RAVE has caused us to improve considerably at Hex.
