### ISSUE TITLE
Local Search causes us to give up too early!

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#242]
In this match: http://www.ggp.org/view/tiltyard/matches/d23d1bce5802f9b4fa761f2be771daebcf575227/ we discovered that our opponent had a forced win at turn 15 (it's FAR from obvious at that point to a human), but because we discover this by eliminating possible moves one at a time, we wind up marking he MCTS tree as complete and then choosing random moves from then on.  We really need a way to let MCTS continue in such situations and make the best of it that it can, since it's highly unlikely our opponent knew it had won.

**Comment by arr28** [comment]
And not just in the local search case, but in all cases where we think we've determined a sub-optimal result, we should play on.

**Comment by SteveDraper** [comment]
Non local-search cases are a bit different since the MCTS tree has
converged itself to a loss, so we cannot use regular MCTS to play on so
easily.  However, in THOSE cases we know which moves lead to the longest
paths and chose them anyway, so that's likely to be about as good as we can
get.  Tryign to do better in the pure MCTS case should not really be the
same issue I think.
