### ISSUE TITLE
Puzzle completion not working

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#255]
Steve,

We're failing each of hunter, hamilton and multiplehamilton.  In each case, early on we claim to have a complete root, scoring the best score (100 for the hamiltons and 87 for hunter).  However, as the game progresses, we suddenly decide that we've got a lower score.

This was working within the last few days, but seems to have regressed.

**Comment by arr28** [comment]
Exact same set of failures in builds 136 and 137.  Also failing locally (StanfordGameTest).

**Comment by arr28** [comment]
Is this all working now?

**Comment by SteveDraper** [comment]
Yes, was yesterday anyway

**Comment by arr28** [comment]
Great.  Closing.
