### ISSUE TITLE
Stop meta-gaming when we've found a solution

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#266]
Successfully cached plan from A* should cause immediate return from meta gaming

**Comment by arr28** [comment]
Likewise if we're playing from a learned plan.  Or, once I've implemented #249, if we find a perfect score during meta-gaming.

Need to make sure that we still do meta-gaming when playing from a partial test plan.

Finally, I notice that there's a commit against this issue, but it's still open.  Did you just forget to close it or are you anticipating doing more?  (Feel free to assign to me to sort out the follow-on things commented here.)

**Comment by SteveDraper** [comment]
Forgot to close, but since you point out these other cases, in an area you
are actively working, I'll assign to you.

**Comment by arr28** [comment]
If we're playing from a learned plan, we already immediately immediately quit meta-gaming and perform the plan.

```java
    // Check if we already know how to solve this game.
    String lSavedPlan = mGameCharacteristics.getPlan();
    if (lSavedPlan != null)
    {
      // We've played this game before and know how to solve it.
      LOGGER.info("Considering saved plan: " + lSavedPlan);
      mPlan.considerPlan(convertPlanString(mGameCharacteristics.getPlan()));
      LOGGER.info("Ready to play");
      return;
    }
```

**Comment by arr28** [comment]
That only leaves the case where we find a perfect score during meta-gaming.  Depending on your p.o.v. it might be correct that we don't immediately play the first solution that we discover.  This gives us time to find a shorter solution thereby looking half-competent in puzzles like Chinese Checkers where otherwise we've been known to throw in a few no-ops.

Closing.

**Comment by SteveDraper** [comment]
But doesn't that mean we can luck-out during meta-gaming and find a path
that scores 100, but then not find it in regular searching?  Or are you
saying that that case has now been tackled, and its just that we don't
signal readyness to play that plan immediately (as opposed to not caching
it at all)?

**Comment by arr28** [comment]
Under this issue, I'm just saying that we won't signal immediately readiness.

I'll sort out plan caching under #249.
