### ISSUE TITLE
Guess two thirds (2 player) detected as iterated game!

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#267]
Detecting a 1-move game as iterated cannot possibly make sense!

**Comment by arr28** [comment]
For our current definition of "iterated", which is more like "has some game theory that we might want to apply to it", it probably does.

All the same, in the 2-player version of guess 2/3rds, we should *always* play zero.  It is a best response to every possible move by the opponent.

**Comment by SteveDraper** [comment]
Well, if the code we applied did things like looking for Nash equilibria
then it might well make sense, but what it actually does is look to find
best response based on assuming the opponent will repeat previous responses
made on earlier moves, which makes no real sense if the game only lasts 1
move!  I think I'll probably ad an at-least-N-turns condition to trigger
use of that player for now.  Replacing it entirely with a 'game theoretic'
player more generally would certainly be good, but I think it's a bit of a
stretch to claim that it is that currently.  MCTS dos at least converge to
0 on Guess 2 thirds (2p), so it's pragmatically a much better choice (and
likely currently the only very short game that potentially uses this player)

**Comment by arr28** [comment]
Agree - that sounds like the pragmatic approach.

**Comment by SteveDraper** [comment]
Done as proposed and checked we now play ( guess 0 )
