### ISSUE TITLE
Impossible completion depth

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#277]
In this [match of Kalaha](http://www.ggp.org/view/tiltyard/matches/df6a8b488c49164fba6e6c5103c02d78e187a912/)...

```
08:27:39.209 - Starting turn 167
<...>
08:27:39.224 - Move ( put p3 ) scores 93.27 (selectionScore score 93.27, selection count 10953679, ref 85899978056, complete [-80])
```

Completion depth of -80?!

**Comment by SteveDraper** [comment]
I think this happens when there are transpositions into states that could
have been reached from shallower levels of the tree (not sure though).
Could just add an assert for >= 0 and see what the situation is when it
goes off.

**Comment by SteveDraper** [comment]
I have been unable to reproduce this per se, but have added the necessary assertions and found one case that lead to a shallower completion depth than a node should have, so it **could** be the root cause.  Also found some other (unrelated) assertion-caught issues.
