### ISSUE TITLE
LogSummarizer to adaptively send fewer logs as required

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#278]

**Comment by arr28** [comment]
So far, I've only found 1 match which generated more than 1MB of logs (which is the Tiltyard limit, I think).  Several others failed to upload.  Looking back at my emails with Sam, last time this was unreliable, it turned out to be a timeout issue.

I've emailed Sam saying it can take us ~10s to reformat the logs + a network RTT.  (I think the largest I've seen is 7s, but that should hopefully leave some headroom.)

**Comment by arr28** [comment]
If we're over the limit, we remove the logs and just return the graphs.  Leaving this open to see what Sam says about the matches where we aren't over the limit.

**Comment by arr28** [comment]
Sam has added some additional logging to the ggp-base version of `LogSummarizer` and asked us to run with it (and send him the output).  I've integrated those changes and intent to restart my `LogSummarizer` this evening.

**Comment by SteveDraper** [comment]
I have just restarted with the new version myself.

**Comment by arr28** [comment]
Thanks.  If there's a game that doesn't upload properly, please can you add the relevant output from the `LogSummarizer` to this issue.

**Comment by SteveDraper** [comment]
No log upload for
http://www.ggp.org/view/tiltyard/matches/08f3b04ea747ac7848f73c27c42cce149d5fdd53/

Summarizer output was:

Generating logs for tiltyard.connectFourv0.1436196551213 at 1436198764815
Took 423ms to generate 658463 bytes of logs for
tiltyard.connectFourv0.1436196551213
Generating logs for tiltyard.connectFourv0.1436196551213 at 1436198767000
Took 2515ms to generate 658483 bytes of logs for
tiltyard.connectFourv0.1436196551213
Generating logs for tiltyard.connectFourv0.1436196551213 at 1436198949217
Took 498ms to generate 658483 bytes of logs for
tiltyard.connectFourv0.1436196551213
Generating logs for tiltyard.connectFourv0.1436196551213 at 1436198951503
Took 2452ms to generate 658483 bytes of logs for
tiltyard.connectFourv0.1436196551213

**Comment by arr28** [comment]
That isn't running the new code.  If running from a jar, have you rebuilt the jar?  (The LogSummarizer one.)

**Comment by SteveDraper** [comment]
I just run LogSummarizer from Eclipse (havign updated to latest code).  Why
would that not be running latest?

**Comment by arr28** [comment]
The logs should look like this.  Note that timestamp before each log and (critically for Sam), the post-response log.

```
1436204617807: Got request for logs for tiltyard.gt_staghuntv0.1436201954564
1436204624322: Got 18955 bytes of logs for tiltyard.gt_staghuntv0.1436201954564
1436204624323: Took 7261ms to generate the logs
1436204624375: Successfully replied to log request for tiltyard.gt_staghuntv0.1436201954564
```

**Comment by arr28** [comment]
Tiltyard's pretty dead.  No longer care about this.
