### ISSUE TITLE
Take another look at intermittent snap-ci tests

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#279]

**Comment by arr28** [comment]
The several recent intermittent failures of the stanford puzzles was caused by #284.  I've fixed half.  Half with Steve.

Hopeful that the intermittent failures of the 2nd set of base puzzles will be fixed by #249.  However, leaving this open until we've had a clean run.

**Comment by SteveDraper** [comment]
Main residual cause appears to be a problem in the way the game searcher is terminated, which freed out a (static) instance used as a buffer before the search thread had actually terminated

**Comment by SteveDraper** [comment]
Spoke too soon.  Peg still failed with no moves to select, at the end of a game in which it DID have a cached plan (SNAP run #233)

**Comment by arr28** [comment]
You fixed this with d384d03.
