### ISSUE TITLE
Broken assertion is normalizeScores

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#283]
Whilst running with assertions enabled to investigate #271, I keep hitting the following assert in `TreeNode.normalizeScores`.

```java
            if ( chooserScore == highestScore/100 )
            {
              assert(Math.abs(weight-edge.getNumChildVisits()) < EPSILON);
            }
```

I'm just going to comment it out for now, but please could you take a look Steve?

(Reliably hit on the first turn of TTT.)

**Comment by SteveDraper** [comment]
Ah - I added it as a validation check but it won't hold in the case of
complete with everything being losses I think.  I'll run and check with
TTT.  I think it's the 'highestScore == 0 case that is liekly to be
problematgic

**Comment by arr28** [comment]
In case it helps, on one occasion when I hit it, the left side of the
assert was 271.999999991 (=272) and the right side was 161.

**Comment by SteveDraper** [comment]
Erroneous assumption (just in the assert) that same score => same node.  Once things start to complete and move to discrete scores as a result this is a very inaccurate assumption!
