### ISSUE TITLE
Assert playing breakthrough

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#285]
Playing [this match of Breakthrough](http://www.ggp.org/view/tiltyard/matches/f45c6ceea1c6fd9c545e5ad64352d82f5e9ca59b/) (small), with assertions on, Sancho asserted on turn 17.

```
Caused by: java.lang.AssertionError
	at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.checkChildCompletion(TreeNode.java:1642)
```

**Comment by arr28** [comment]
Low priority.  When we come back to it, I was probably playing with latest commit d2ef5c578cb61cd4dd2ec6efab6cc9eace3c3cd1 (or thereabouts - no relevant changes recently anyway).

**Comment by SteveDraper** [comment]
This just happened to me also (in Breakthrough again).  Will set it running debug and see if I can reproduce...
