### ISSUE TITLE
Incorrect selection of factor to play from in BrkThru/walls

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#289]
In http://www.ggp.org/view/tiltyard/matches/6d48615bb90d21101168c7848a9249c7350dbb02/ on turn 34 we played from the right hand semi-board instead of the free capture on the left.  Logs show right hand tree had selected almost entirely through the pseudo-noop (to an extent that seems unlikely to be correct, which is likely a secondary bug), but then treated a non-complete score of 100 in a node with one playout as being a win, and hence preferentially selected it!

**Comment by arr28** [comment]
Is this fixed?

**Comment by SteveDraper** [comment]
Oh yes.  Forgot to close
