### ISSUE TITLE
Amazons on a torus 10X10 fails to build propnet and then hangs

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#290]
Not so much the failure to build the propnet (though that is a bug, even if likely hard to solve), but failure to handle the error with a result that just hangs things up even though it clearly detects the error situation inside propnet creation (which means we should be able to handle it by aborting and not require the game to be poisoned)

**Comment by SteveDraper** [comment]
Upped this to P1, since it totally kills overnight Tiltyard sessions currently

**Comment by SteveDraper** [comment]
Fixed the underlying cause (the handling of the loops in the propnet).  However, leaving this issue open for you, since the watchdog did not recover the situation despite going off and generating completed tidy-up logs.  You may need to regress this fix in order to reproduce conditions to duplicate that failure mode now.

**Comment by arr28** [comment]
I fixed the residual issue under #272.
