### ISSUE TITLE
We seem to think we're playing suicide at Amazons when we are not!

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#293]
http://www.ggp.org/view/tiltyard/matches/10719629b07de35e162c854f51702c244535a55e/

**Comment by SteveDraper** [comment]
Logs show we thought we'd won when we lost, so the goals calculation must be backwards somehow...

**Comment by SteveDraper** [comment]
Two bugs here:

Firstly a relatively minor one in the heuristics analyser that passed the penultimate state (instead of the terminal state) to heuristic analysers at the ends of sample games

Secondly the key one - Amazons (10X10) and Amazons Suicide (10X10) have IDENTICAL GDL apart from the goal values (0 and 100) which are swapped.  Out GDL translator cached an identity mapping for the first of these games to be played, and then proceeding to claim the second one played was the same with the GDL atoms 0 -> and 100 -> 0 !!

**Comment by arr28** [comment]
Yes, that doesn't surprise me (see email from a few minutes ago when I
suggested deleting the game directories).  Fix is probably to beef up the
matching code so that it isn't willing to map any of the numeric symbols
from 0 - 100.

I'm happy to do that if you want.

Andrew
