### ISSUE TITLE
Crashes in dual/simultaneous C4

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#301]
stanford.dualconnectfour and base.connect4simultaneous (which aren't the same game, at least as far as our current GDL matching goes) both reliably cause crashes during meta-gaming.

(This happened before the refactoring of the factor analysis code, but I haven't searched back through the history.)

**Comment by arr28** [comment]
Exception is...

```
[GamePlayer] java.lang.NullPointerException
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.transitionToRandomJointMove(ForwardDeadReckonPropnetStateMachine.java:4015)
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getDepthChargeResult(ForwardDeadReckonPropnetStateMachine.java:4333)
	at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:774)
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208)
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70)
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111)
```

**Comment by arr28** [comment]
Steve, this was caused by one of your 9 commits on 20th June - between 1ed4655301bc6b21eb0719be71db393208d9cfd6 "Added toString() to TreePath..." and 7e35747c76ec33236cd536d191c00f08dcd3d2f1 "Fixed bug in policy move pop handling that lead to incorrect plans being cached for KnightsTourLarge" inclusive.  I'll do more chopping later.

**Comment by SteveDraper** [comment]
I'll get to it as soon as I sort out the checkers thing (making progress -
will update you tomorrow with status)

**Comment by arr28** [comment]
Sounds promising.  For this bug I note that Chinook is also broken but that other games with factors are fine.  For the single-player factoring games, that might just be because we're using a learned solution, but for other 2-player games (e.g. breakthrough w/ walls, it's doing fine).

**Comment by arr28** [comment]
Problem was introduced in commit d809a748bcff09fcb9c85f8a21da9256dabd0766 ("Some refactoring and enhancement of support for playout policies").

Oddly, running with assertions enabled, doesn't hit the "chosen != null" assert 5 lines earlier and it can't be nulled out in those lines.  And yet when under the debugger (breakpoint on NullPointerException), chosen == null.

**Comment by arr28** [comment]
Scratch what I said about not hitting the "chosen != null" assertion.  That's because I didn't actually have asserts enabled.  When running with asserts, we hit `assert(choiceIndex < numChoices);` above.

I don't really understand the code, but I'm suspicious that you don't reset `choiceIndex = -1` each time round the for(role) loop.

**Comment by arr28** [comment]
Actually, looking at the change that was made, I wonder if it needs to be reset each time round the `do {...} while (!acceptableChoice);` loop.

**Comment by arr28** [comment]
Actually, inside the `do/while` loop doesn't help.  Resetting `choiceIndex = -1` Inside the `for(role)` loop seems to stop the crashes.  No idea if it's (a) correct or (b) complete though.  I'm going to stop hacking around at this point and turn it over to you, Steve.

To be clear, my hint is to add `choiceIndex = -1` immediately inside the loop `for (int roleIndex = 0; roleIndex < numRoles; roleIndex++)` in `transitionToRandomJointMove`.

Otherwise, when looking at the second role, we don't go through the `if ( choiceIndex == -1 )` branch a few lines later.  So `choiceIndex` doesn't get set to a valid value.  Therefore it can be out of range, triggering the assert (if enabled) or causing us not to set `chosen` because the loop over `numChoices` never reaches `moveIndex` (copied from `choiceIndex`).

Having written all that, I'm now sure enough to check this in.  But please can you carefully review.  (Leaving issue open and assigning to you until you've done that.)

**Comment by arr28** [comment]
Steve - this fix was not right.  It led to an infinite loop in hunter (which has a greedy policy w/ pop).  I've backed it out.

**Comment by arr28** [comment]
Sorry Steve - still not fixed.

Both [this match](http://www.ggp.org/view/tiltyard/matches/400081d60901391e19a0a49aca92b62385ecab28/) and [this one](http://www.ggp.org/view/tiltyard/matches/df4ab9017bfc186bcae5541d0ecc51e827bfe24a/) crashed for me last night.  Logs for both matches available on Tiltyard.

Died during MG both times.

```
02/07/2015 05:56:46.292	ERROR	Exception in player during meta-gaming
java.lang.NullPointerException\n at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getNextState(ForwardDeadReckonPropnetStateMachine.java:2940)\n at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3322)\n at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2579)\n at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.setRootState(MCTSTree.java:768)\n at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.startSearch(GameSearcher.java:951)\n at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:1104)\n at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208)\n at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70)\n at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111)\n
02/07/2015 05:56:46.294	WARN	[GamePlayer] java.lang.NullPointerException at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getNextState(ForwardDeadReckonPropnetStateMachine.java:2940) at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3322) at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2579) at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.setRootState(MCTSTree.java:768) at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.startSearch(GameSearcher.java:951) at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:1104) at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208) at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70) at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111)
02/07/2015 05:56:46.295	WARN	[GamePlayer] An unhandled exception occurred during metagaming: org.ggp.base.player.gamer.exception.MetaGamingException: java.lang.NullPointerException at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:214) at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:70) at org.ggp.base.player.GamePlayer.run(GamePlayer.java:111) Caused by: java.lang.NullPointerException at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.getNextState(ForwardDeadReckonPropnetStateMachine.java:2940) at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expandInternal(TreeNode.java:3322) at org.ggp.base.player.gamer.statemachine.sancho.TreeNode.expand(TreeNode.java:2579) at org.ggp.base.player.gamer.statemachine.sancho.MCTSTree.setRootState(MCTSTree.java:768) at org.ggp.base.player.gamer.statemachine.sancho.GameSearcher.startSearch(GameSearcher.java:951) at org.ggp.base.player.gamer.statemachine.sancho.Sancho.stateMachineMetaGame(Sancho.java:1104) at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:208) ... 2 more 
``` 

Oddly, you played with me in the first match and didn't seem to crash.  According to my logs, I was playing with this version.

```
02/07/2015 05:54:38.916	INFO	This is Sancho 1.60y with last commit 3caf9db66a4d307b00d137b1519b66352c72237f
```

You haven't set WC_LOCATION, so I don't know what you were playing with.  However, I don't see anything since 3caf9db66a4d307b00d137b1519b66352c72237f that's likely to be relevant here.

**Comment by arr28** [comment]
Same problem in Chinook ([here](http://www.ggp.org/view/tiltyard/logs/ac8a43c5094e994dcd8964bd7688e930c17dbc2f/Sancho_Dev_ARR)).  So probably factor-related.

**Comment by SteveDraper** [comment]
Did you try with assertions enabled?  It asserts for me unable to find
props trying to reload the factors from learnt previous runs.  When I
regression tested previously I likely had learning disabled - this appears
to be a factor serialization issue

**Comment by arr28** [comment]
I confirm that I'm still seeing it with the current code.  One of the moves (the second in this case) passed in to `FDRPSM.getNextState` is `null` (the other being oddnoop).

**Comment by arr28** [comment]
Ah, okay - I will take.

**Comment by SteveDraper** [comment]
...and found it.  Will verify I can reproduce with cleared and re-saved
learnt data, and then that it fixes it...
