### ISSUE TITLE
hmm - maybe we should disable chat integration for unit tests!!

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#329]
During qualifiers the chat channel I'd want to use (the default one) is being spammed by unit tests from SnapCI!  Although I could configure a non-default one I'd really rather have the canonically named one kept clear.  Suggest we either disable for unit tests, or run with a different config there to use a different channel explicitly

**Comment by arr28** [comment]
Will fix - but I suggest you don't tell people about the chat until the finals.  Don't want to ruin the fun!

**Comment by arr28** [comment]
Done.  When running from snap-ci, it'll log to sanchosnap.
