### ISSUE TITLE
stanford.chinook is broken

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#331]
Causes us to select illegal moves all the time.

```
08:54:44.250 ? Selected illegal move!!
```

Not (directly) related to learning because it happens with learning turned off.  Might have been caused by the factor refactoring though.

**Comment by arr28** [comment]
This is specifically an issue with stanford.chinook.  base.chinook is fine.

**Comment by SteveDraper** [comment]
Would you like me to look into this later today (won't be in time for your qualifier, but that should not matter)?

**Comment by arr28** [comment]
I'm just binary chopping just now.  Succeeded on 31st May, but failed on
11th June.  I'll update you again when I get closer.

**Comment by arr28** [comment]
Steve,

The problem appears to have been introduced when you added RAVE - i.e. between "#284 Consistent handling of factorization in regard to plan caching" (b9876ff7cf8af2e0af1c51cbecc86fab517cefd2) and "#249 - corrected SNAFU in the refactoring that caused it to try to cache plans for non-puzzles!
Initial RAVE integration (turned off in config by default)" (41c794ab097af54a3af8a91700761e8439305596) inclusive (on 6th - 7th June).

If you could have a look, that would be great.

Note that (despite the original title of this bug), I don't actually have any evidence that it's related to factoring.

**Comment by SteveDraper** [comment]
Actually it was broken on March 5th by code that integrated local search! ('Integrate local search into regular move searching to perform local search on candidate MCTS-determined move').

Fix is pretty obvious and seems to solve the problem.

**Comment by SteveDraper** [comment]
Hmm - I pushed a syntax error (which in itself is obvious, but how did my regression test work here!??).  Retesting with syntax error corrected!

**Comment by SteveDraper** [comment]
ah - its because Andrew added an 'm' prefix to a member name and the auto-merge had no way to spot it.

**Comment by arr28** [comment]
I've just fixed (and pushed) a fix for the auto-merge failure.
