### ISSUE TITLE
Invalid propnet generated for Hidato

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#360]
I've produced a version of Hidato.  We don't produce a valid propnet for it.  It could easily be an error in the GDL, but...

- Griddle says it's clean
- [Stepper](gamemaster.stanford.edu/gamestepper.php) simulates it correctly
- The Server app appears to correctly calculate the legals
- Alloy can solve it correctly

Sancho produces too many legals.  The conditions for a placement to be legal are...

```
; A number n can be placed in cell c iff...
;
; - c is blank.
; - n is not already present.    
; - n-1 is either not present or is adjacent to c.
; - n+1 is either not present or is adjacent to c.

(<= (legal robot (place ?c ?n1))
    (true (cell ?c blank))
    (unused ?n1)
    (succ ?n0 ?n1)
    (succ ?n1 ?n2)
    (absent_or_adjacent ?n0 ?c)
    (absent_or_adjacent ?n2 ?c))

(<= (unused ?n)
    (number ?n)
    (not (used ?n)))

(<= (used ?n)
    (true (cell ?c ?n)))

(<= (absent_or_adjacent ?n ?c)
    (coord ?c)
    (unused ?n))

(<= (absent_or_adjacent ?n ?c1)
    (true (cell ?c2 ?n))
    (adjacent ?c1 ?c2))
```

At some point in the optimization process (yet to be determined - but certainly by "propnet_040_Reduced"), we end up with logic of the following form feeding the legals.

![image](https://cloud.githubusercontent.com/assets/3194913/9352490/97e27f34-4659-11e5-9288-8936477a8a03.png)

i.e. we only check that the target cell is blank.  We don't attempt to check that the number hasn't been played yet and we don't attempt to check the adjacency requirements.

**Comment by arr28** [comment]
The problem already exists by "propnet_020_BeforeLargeFanout".

I speculatively removed the call to `OptimizingPolymorphicPropNetFactory.removeIrrelevantBasesAndInputs` and that solved the problem (and then Sancho solved the puzzle in 250ms, without engaging the partitioner).

**Comment by arr28** [comment]
This appears to be a failure of `recursiveFindReachable`.  The propnet has >2K components.  After the call to...

`recursiveFindReachable(pn, pn.getTerminalProposition(), reachableComponents, null );`

...288 are declared reachable.  This _might_ be right (but see below).  It contains all the "blank" props, the "finished" prop and various connective logic.

However, adding in the logic leading to our goals...

```
      for( PolymorphicProposition c : pn.getGoalPropositions().get(ourRole))
      {
        recursiveFindReachable(pn, c, reachableComponents, null );
      }
```

...gives just 2 more props for each of the 2 goals (0/100) for a final total of 290 reachable components.

The goals are...

```
(<= (goal robot 0)
    (true (cell ?c blank)))

(<= (goal robot 100)
    (not (goal robot 0)))
```

..which means it isn't surprising that we only add 4 more components.  That's because...

- One of the terminal conditions is "no more blank cells"
- The 0 goal condition is "any blank cells"
- The 100 goal condition is !(0 goal).

So, anything that wasn't reachable for terminality won't become reachable for the goals.  So that leads me to ask why 90% of the game isn't considered reachable for terminality.  Since one of the terminal conditions is "no blank cells" and cells lose their "blank" status when played on, that ought to make all the legals part of the (backwards) reachable set.  The relevant rules are...

```
(<= (next (cell ?c1 blank))
    (true (cell ?c1 blank))
    (does robot (place ?c2 ?n))
    (distinct ?c1 ?c2))

(<= (next (cell ?c blank))
    (true (cell ?c blank))
    (does robot quit))
```

...so I wonder if we're having some issues going backwards through the `distinct`.

**Comment by arr28** [comment]
Honing in now.  In `recursiveFindReachable`, this looked suspect to me...

```
    if ( pn.getBasePropositions().values().contains(from))
    {
      viaBaseProp = (PolymorphicProposition)from;
    }
<...>
    else if ( viaBaseProp != null && (from instanceof PolymorphicAnd) )
    {
      //  Don't traverse conditions that just preserve an already set base prop, since
      //  such a path cannot CAUSE it to become set
      if (from.getInputs().contains(viaBaseProp))
      {
        return; // !! ARR This is dodgy
      }
    }

    for(PolymorphicComponent c : from.getInputs())
    {
      recursiveFindReachable(pn, c, reachableComponents, viaBaseProp);
    }
```

Commenting out the dodgy line (whilst leaving the rest of the optimization in place) causes us to solve the problem.  I have a hunch that there's going to be a `NOT` involved.

The code in question is trying to identify logic of the form `prop(t1) = condition AND prop(t0)` and then say that that logic can't be responsible for setting the proposition, so we shouldn't follow it backwards.

However, if the condition being calculated is more along the lines of `prop(t1) = condition AND NOT prop(t0)`, we'd still exclude the relevant logic even though it could cause the proposition to become set.

I'm inclined to add a simple test to that routine which clears `viaBaseProp` when it meets a `NOT`.

It's never wrong to leave logic in (i.e. we won't generate an invalid propnet by leaving extra logic in) but we might fail to remove some chunks of network and, critically, we might fail to identify a pseudo-puzzle.

Steve - do you know what game(s) the bit of code marked as dodgy was added for (so that I can test those specifically)?

**Comment by SteveDraper** [comment]
It was one of the pseudo-factorized games I think - the puzzles that have
irrelevant factors.  Does blame point at a commit that has any useful info?

**Comment by arr28** [comment]
I'll have a look.  Also, the simple test and clear `visBaseProp` doesn't actually solve the problem, so more analysis is required.

**Comment by arr28** [comment]
Aha, in this case it's because the `cell X blank` propositions are `init`ially true.  For any such propositions, we presumably ought to be tracing back any paths that might lead them to become **false**?  Or is that particular to this puzzle where we've already passed a `NOT` on the reverse path from `terminal` (which is the proposition we're calculating reachability for)?

Either way, the bad news here is that we can't guarantee the order in which we trace back.  So if we get to an `AND` before finding a sibling/cousin/aunt/etc. `init`, then we won't know at that point that we need to keep tracing back.

I also think my previous comment about the `NOT` bug still stands - it just isn't directly relevant in this case.

**Comment by arr28** [comment]
I have a fix for the `NOT` bug.  I also have a hacky fix for the `init` bug.  It does a *very* crude search to find propositions that are initially true (because we can't use the normal method for calculating the initial state at this point in the optimization process) and then skips the `viaBaseProp` abort logic for initially true propositions.

This fixes Hidato.

Looking back through the log, the `viaBaseProp` logic was added to get factoring working for MultipleHamilton (under #234).  I'll test against that before I commit.

**Comment by arr28** [comment]
Sadly it seems to break irrelevant state removal for MultipleHamilton.  The left board is irrelevant, but `( location left a )` is initially true.  Marking that branch of logic as reachable (in `recursiveFindReachable`) leads to the whole left board being kept alive.

**Comment by arr28** [comment]
This is doing my head in.

Looking at multiple hamilton.  Without my fix, Sancho prunes everything above an AND feeding `score right 5`.  However, because this proposition is initially true, with my fix, we don't prune at that point.  Instead, we keep working backwards through the graph, marking nodes as reachable.

Unfortunately, that includes a whole load of `left` propositions.  I *think* that'll be due to this rule...

```
  (<= (next (score ?s ?n))
      (does robot (move ?r ?y))
      (true (score ?s ?n))
      (distinct ?r ?s))
```

...i.e. the score on board X stays the same if the player plays on board Y.  Due to the `distinct` construction, all the `DOES` props on the left board appear to affect the score on the right.  Then we follow back through the `DOES/LEGAL` linkage and suddenly the whole of the left board is apparently affecting the right - so we keep it alive.

I haven't yet figured out what I need to do to throw away the left board in Multiple Hamilton but keep the `cell X blank` logic alive in Hidato.

Any ideas Steve?

**Comment by arr28** [comment]
(I think there's an optimization step which undoes some of the adverse effects of `distinct` and turns it into a `not`.  At as guess, that's either `refactorLargeGates` or `refactorLargeFanouts`.  Either way (and even if it's something different), it probably happens after `removeIrrelevantBasesAndInputs`.  However, I'm guessing that reordering won't help in this case because there'll be as many legals on the right board as there are on the left, so we'll see no reason to replace all the left legals with all the right legals - probably.)

**Comment by arr28** [comment]
Following discussion with Steve, fix is probably...

- Do pruning as currently for initially false propositions
- Don't prune above propositions that are initially true
  - Unless they are initially true goal propositions

The reason being that, for goal propositions, if the true one becomes false, another one must become true.  Therefore, we'll find the relevant logic when tracking back from the goal that's going to become true.

Note that this isn't technically correct.  If there's more than one initially true goal proposition then the above doesn't hold.  In particular, imagine a (fairly realistic) GDL formulation where all the goal values were initially true, but they get knocked off one-by-one until only 1 remains - at which point the game is terminal.  In such a game, we'd probably prune out the whole game.

**Comment by arr28** [comment]
Still no joy.

In Multiple Hamilton, the `score` props are proxies for the corresponding `goal` props.  So there are no goal props that are considered to be initially true.  (Using the Prover to get the initial state - it doesn't report `goal robot 5` as initially true, even though `score right 5` is initially true and the goal rule is `(<= (goal robot ?n) (true (score right ?n)))`).  Therefore, we don't identify `score right 5` as anything special so, with my fix for Hidato, we still don't prune Multiple Hamilton properly.

**Comment by arr28** [comment]
Steve,

As above, I'm still failing to solve this.  Any chance you could look at this one?

Andrew

**Comment by SteveDraper** [comment]
Down to the last comment but one I think you were on the right track (or at least not reached a dead end, and still worth further exploration), which is where I'd like to take things up.  However, to do this (without spending a lot of time duplicating what you've already done) I need the code you had that:
1) Determines the initial state (hackily or otherwise)
2) Gates the trimming through props that are true in the initial state
Meanwhile I'll explore why the goal 5 is not initially set in Multiple Hamilton, since it sounds like it really should be (and if not then [based on what I find] how we could treat it as if it were based on the score prop).
Could you check your code (for (1) and (2) above) in on a branch please

**Comment by SteveDraper** [comment]
I'm a little confused.  I added this code to the start of the state machine initialization routine:

    ProverStateMachine prover = new ProverStateMachine();
    prover.initialize(description);
    MachineState pInitialState = prover.getInitialState();
    for(Role r: prover.getRoles())
    {
      try
      {
        LOGGER.info("Role " + r + " has initial goal value " + prover.getGoal(pInitialState, r));
      }
      catch (GoalDefinitionException e)
      {
        // TODO Auto-generated catch block
        e.printStackTrace();
      }
    }

For multiple Hamilton I get the log:

Role robot has initial goal value 5

Which is what we want, but seems to contradict Andrew's earlier finding.  Awaiting clarification and branch (or other copy will do out of band if preferred) of the code that modifies the trimming based on initially set props and goals...

**Comment by arr28** [comment]
Suspect the discrepancy is that I called `getInitialState()` and then read off the propositions that were true.  Thinking about that in light of your comment above (and the call to `getGoal`), the prover presumably hasn't done its equivalent of propagation (because it doesn't really have an equivalent) and therefore I don't see that goal prop as being set.  It's only when you specifically ask the prover the question that you get an answer.

I'd binned all my code, but am reconstructing it now.

**Comment by arr28** [comment]
Steve,

I've reconstructed most of my work and pushed it to the `issue360` branch.  The only bit I haven't put back is the "Unless they are initially true goal propositions" bit because (a) I can't remember exactly how I did that and (b) I no longer think they way I was doing it was right (see previous comment).

With the code as-is on the `issue360` branch, we generate a valid propnet for Hidato, but fail to properly prune Multiple Hamilton.

Can you take it from here?

Andrew

**Comment by SteveDraper** [comment]
Sure

Thnaks

**Comment by SteveDraper** [comment]
Ok, I agree that the whole try-ti-use-the-initial-state thing doesn't work.

The approach that finally did (at least for all extant examples) is as follows (and has the benefit of not requiring prover-based initial state calculations passing in):

1) The 'self-supported base-prop logic does not propagate back through it's self-support AND' remains, but is modified to only apply to base props that are not themselves DIRECTLY required by the terminal calculation or a goal calculation.
2) In the above, a 'direct' dependency is one which does not involve the traversal of a does->legal link (i.e. - a direct dependency on the state, not on a path to the state)
3) Base props that are simply acting as proxies to the goal props are not themselves considered direct dependents.  This is really a bit of a hack that has the effect of allowing the self-support trimming to operation on such proxy propositions.  The (with much hand-waving) justification for this is that at least one goal prop will always be true in any valid terminal state, so not tracking back through the self-support logic must leave other logic which feeds CHANGES to the goals intact, which is where the 'real' dependency lies.  Admittedly this is in no way a rigorous justification, but it at least has some theoretical support (previous sentence) and seems to work!

Once debugged, the above approach worked for Hidato and Futoshiki, while still correctly trimming multiple Hamilton (and the other multiple-X games).

Currently running full regression suite...
